data-dir = "/mnt/sdb/summarystore"
results-dir = "/home/sstore/summarystore/code/SummaryStore/output"
window-cache-size = 1_000_000
ingest-buffer-size = 2_000_000      # number of values to buffer before triggering merge

# List of decay functions. Allowed vals: exponentialBASE, rationalPowerP,Q,R,S
decay-functions = [
"exponential2",
"rationalPower1,1,1,1",
"rationalPower1,1,2,1",
"rationalPower1,1,4,1",
"rationalPower1,1,8,1",
"rationalPower1,1,16,1",
"rationalPower1,1,32,1",
"rationalPower1,1,64,1",
"rationalPower1,1,128,1",
"rationalPower1,2,1,1",
"rationalPower1,2,2,1",
"rationalPower1,2,4,1",
"rationalPower1,2,8,1",
"rationalPower1,2,16,1",
"rationalPower1,2,32,1",
"rationalPower1,4,1,1",
"rationalPower1,4,2,1",
"rationalPower1,4,4,1",
"rationalPower1,4,8,1",
"rationalPower1,4,16,1",
"rationalPower1,4,32,1",
]
operators = ["SimpleCountOperator", "SumOperator"]


[data]
tstart = 946684800000000000
tend = 978217200000019998
stream-generator = "TSMStreamGenerator"
file = "/home/sstore/summarystore/code/SummaryStore/workloads/tsm/tsm.sstore"
operators = ["SimpleCountOperator", "SumOperator"]


[workload]
workload-generator = "TSMWorkloadGenerator"


[performance]
parallel-workload-gen = true
drop-caches = true
