data-dir = "/mnt/sdc/summarystore"
results-dir = "/home/sstore/summarystore/code/SummaryStore/output"
bucket-cache-size = 1_000_000
ingest-buffer-size = 2_000_000

decay-functions = [
"exponential2",
"rationalPower1,1,1,1",
"rationalPower1,1,2,1",
"rationalPower1,1,4,1",
"rationalPower1,1,8,1",
"rationalPower1,1,16,1",
"rationalPower1,1,32,1",
"rationalPower1,1,64,1",
"rationalPower1,1,128,1",
"rationalPower1,2,1,1",
"rationalPower1,2,2,1",
"rationalPower1,2,4,1",
"rationalPower1,2,8,1",
"rationalPower1,2,16,1",
"rationalPower1,2,32,1",
"rationalPower1,4,1,1",
"rationalPower1,4,2,1",
"rationalPower1,4,4,1",
"rationalPower1,4,8,1",
"rationalPower1,4,16,1",
"rationalPower1,4,32,1",
]
operators = ["CMSOperator5,504"]


[data]
tstart = 1420070400000000000
tend = 1451606399000000004
stream-generator = "ReplayStreamGenerator"
file = "/home/sstore/summarystore/code/SummaryStore/workloads/mlab/paris-serverIPs.sstore"


[workload]
workload-generator = "MLabWorkloadGenerator"
cms-operator-index = 0
mode = "server"


[performance]
parallel-workload-gen = true
drop-caches = true
