data-dir = "/mnt/md0/sstore"                # where we store SummaryStore (RocksDB) data
results-dir = "results"             # where we store experiment output
window-cache-size = 1_000_000_000       # number of windows to cache in memory
ingest-buffer-size = 2_000_000      # number of values to buffer before triggering merge

# List of decay functions. Allowed vals: exponentialBASE, rationalPowerP,Q,R,S
# TODO: consider specifying each decay as a map, instead of encoding into string
decay-functions = [
    "rationalPower1,1,8,2", # 10.3% full sstore
    "rationalPower8,1,1,1", # 11% max-only sstore
]

# List of operators to maintain in each SummaryStore
# (names of classes in the com.samsung.sra.DataStore.Aggregates package)
operators = ["MaxOperator"]
#operators = ["SumOperator"]


# Dataset (stream generator) specification
[data]
stream-generator = "BinStreamGenerator"
file = "/mnt/md0/task_usage.bin"
tstart = 0
tend = 2505598000035 # 29 days, values in us
tag-landmarks = {threshold = 137900000}


# Workload specification
[workload]
# Use com.samsung.sra.DataStoreExperiments.CalendarWorkloadGenerator
workload-generator = "GoogleLandmarkWorkloadGenerator"
max-operator-index = 0
threshold = 64328900
ticks-per-second = 1_000_000   # us


[performance]
# Process queries in parallel when generating workload. Adds a couple of
# minutes of stream management overhead, only recommended in large streams
parallel-workload-gen = true   # optional, default false
# TODO: drop kernel page/inode/dentries caches before starting RunComparison
drop-caches = false            # optional, default false
