data-dir = "/mnt/md0/sstore"                # where we store SummaryStore (RocksDB) data
results-dir = "results"             # where we store experiment output
window-cache-size = 100_000       # number of windows to cache in memory
ingest-buffer-size = 1_000_000      # number of values to buffer before triggering merge

decay-functions = [
    "rationalPower1,1,2,5",
]

# List of operators to maintain in each SummaryStore
# (names of classes in the com.samsung.sra.DataStore.Aggregates package)
operators = ["SimpleCountOperator", "SumOperator", "BloomFilterOperator5,1000", "CMSOperator5,500"]
#operators = ["SimpleCountOperator", "SumOperator", "CMSOperator1,2500"]


num-parallel-streams = 10
[data]
nstreams = 10
dimensionality = 1
tstart = 0
tend = 6_250_000_000_000
stream-generator = "RandomStreamGenerator"
interarrivals = {distribution = "ExponentialDistribution", lambda = 0.001}
values = {distribution = "UniformDistribution", min = 1, max = 100}
random-seed = 0                              # RandomStreamGenerator seed. Optional, defaults to 0


[workload]
workload-generator = "CalendarWorkloadGenerator"
operators = [
  {index = 0, type = "count"},
  {index = 1, type = "sum"},
  {index = 2, type = "bf", param = {distribution = "UniformDistribution", min = 1, max = 100}},
  {index = 3, type = "cms", param = {distribution = "UniformDistribution", min = 1, max = 100}}
]
ticks-per-second = 1_000_000   # usec


[performance]
parallel-workload-gen = true
drop-caches = false
