data-dir = "/mnt/sdb/summarystore"
results-dir = "/home/sstore/summarystore/code/SummaryStore/output"
window-cache-size = 1_000_000
ingest-buffer-size = 2_000_000

decay-functions = [
"rationalPower1,1,2,1",
]
operators = ["SimpleCountOperator", "SumOperator", "BloomFilterOperator5,1000", "CMSOperator5,1000"]

[data]
tstart = 0 # ms
tend = 31_536_000_000 # ms (1 year)
stream-generator = "RandomStreamGenerator"
interarrivals = {distribution = "ExponentialDistribution", lambda = 0.01} # 0.01/ms or 10/s
values = {distribution = "UniformDistribution", min = 1, max = 100}

[workload]
workload-generator = "CalendarWorkloadGenerator"
ticks-per-second = 1000 # timestamps are in ms
operators = [
    {index = 0, type = "count"},
    {index = 1, type = "sum"},
    {index = 2, type = "bf", param = {distribution = "UniformDistribution", min = 1, max = 100}},
    {index = 3, type = "cms", param = {distribution = "UniformDistribution", min = 1, max = 100}},
]

[performance]
drop-caches = true
parallel-workload-gen = true
